TennisBookings.Web/Areas/Admin/Controllers/CourtsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TennisBookings.Web.Areas.Admin.ViewModels;
using TennisBookings.Web.Core;
using TennisBookings.Web.Pages;
using TennisBookings.Web.Services;

namespace TennisBookings.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]")]
    [Authorize(Roles = "Admin")]
    public class CourtsController : Controller
    {
        private readonly ICourtBookingService _courtBookingService;

        public CourtsController(ICourtBookingService courtBookingService)
        {
            _courtBookingService = courtBookingService;
        }

        [HttpGet]
        [Route("Bookings/Upcoming")]
        public async Task<ActionResult> WeeklyBookings()
        {
            var bookings = await _courtBookingService.BookingsUntilDateAsync(DateTime.UtcNow.GetEndOfWeek());

            var bookingsViewModel = bookings.Select(x => new CourtBookingViewModel
            {
                BookingId = x.Id,
                CourtName = x.Court.Name,
                StartDateTime = x.StartDateTime,
                EndDateTime = x.EndDateTime,
                MemberName = $"{x.Member.Forename} {x.Member.Surname}"
            }).GroupBy(x => x.StartDateTime.Date);

            var viewModel = new BookingListerViewModel { CourtBookings = bookingsViewModel, EndOfWeek = DateTime.UtcNow.GetEndOfWeek() };

            if (TempData.TryGetValue("BookingCancelled", out var successObject) is bool success)
            {
                viewModel.CancelSuccessful = success;
            }

            return View(viewModel);
        }

        [HttpGet]
        [Route("Booking/{bookingId:int}/Cancel")]
        public async Task<ActionResult> CancelBooking(int bookingId)
        {
            var courtBooking = await _courtBookingService.LoadBooking(bookingId);

            if (courtBooking == null)
                return NotFound();

            var viewModel = new CancelBookingConfirmationViewModel
            {
                BookingId = bookingId,
                CourtName = courtBooking.Court.Name,
                MemberName = $"{courtBooking.Member.Forename} {courtBooking.Member.Surname}",
                Date = courtBooking.StartDateTime.Date,
                StartTime = courtBooking.StartDateTime.Hour.To12HourClockString(),
                EndTime = courtBooking.EndDateTime.Hour.To12HourClockString()
            };

            return View(viewModel);
        }

        [HttpPost]
        [Route("Booking/{bookingId:int}/Cancel")]
        public async Task<ActionResult> CancelBookingConfirmation(int bookingId, string submitButton)
        {
            if (submitButton == "Cancel")
            {
                return RedirectToAction("WeeklyBookings");
            }

            await _courtBookingService.CancelBooking(bookingId);

            TempData["BookingCancelled"] = true;

            return RedirectToAction("WeeklyBookings");
        }

        /*
         * Action Injection
         */
        [Route("Maintenance/Upcoming")]
        public async Task<ActionResult> UpcomingMaintenance([FromServices] ICourtMaintenanceService courtMaintenanceService)
        {
            var maintenanceSchedules = await courtMaintenanceService.GetUpcomingMaintenance();

            var maintenanceViewModels = maintenanceSchedules.Select(x => new CourtMaintenanceViewModel
            {
                CourtName = x.Court.Name,
                StartDateTime = x.StartDate,
                EndDateTime = x.EndDate,
                Title = x.WorkTitle,
                CourtIsClosed = x.CourtIsClosed
            }).GroupBy(x => x.StartDateTime.Date);

            var viewModel = new MaintenanceListerViewModel { ScheduledMaintenanceWork = maintenanceViewModels };

            return View(viewModel);
        }
    }
}

TennisBookings.Web/Areas/Admin/Views/Courts/CancelBooking.cshtml
@model TennisBookings.Web.Areas.Admin.ViewModels.CancelBookingConfirmationViewModel
@{
    ViewData["Title"] = "Confirm Booking Cancellation";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-12">
        <h2>Are you sure you wish to delete the following booking?</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h3>@Model.Date.ToString("D")</h3>
        <p><strong>@Model.CourtName</strong>: @Model.StartTime to @Model.EndTime</p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <form method="POST">
            <div class="row">
                <div class="col-md-2">
                    <br />
                    <input asp-for="BookingId" type="hidden" />
                    <input type="submit" name="submitButton" value="Confirm" class="btn btn-success" />
                    <input type="submit" name="submitButton" value="Cancel" class="btn btn-warning" />
                </div>
            </div>
        </form>
    </div>
</div>

TennisBookings.Web/Areas/Admin/Views/Courts/UpcomingMaintenance.cshtml
@using TennisBookings.Web.Core
@model TennisBookings.Web.Areas.Admin.ViewModels.MaintenanceListerViewModel
@{
    ViewData["Title"] = "Upcoming Court Maintenance";
}

<h1>@ViewData["Title"]</h1>

@foreach (var date in Model.ScheduledMaintenanceWork)
{
    <div class="row">
        <div class="col-md-12">
            <h2>@date.Key.ToString("D")</h2>

            @foreach (var maintenanceWork in date)
            {
                <div class="@(maintenanceWork.CourtIsClosed ? "alert alert-warning" : "alert alert-success")">
                    <p><strong>@(maintenanceWork.CourtIsClosed ? "CLOSED" : "OPEN")</strong></p>
                    <p>
                        <strong>@maintenanceWork.CourtName</strong>: @maintenanceWork.StartDateTime.Hour.To12HourClockString() to @maintenanceWork.EndDateTime.Hour.To12HourClockString()<br/>
                        <em>@maintenanceWork.Title</em>
                    </p>
                </div>
                }
            </div>
    </div>
}

TennisBookings.Web/Areas/Admin/Views/Courts/WeeklyBookings.cshtml
@using TennisBookings.Web.Core
@model TennisBookings.Web.Areas.Admin.ViewModels.BookingListerViewModel
@{
    ViewData["Title"] = "Upcoming Court Bookings";
}

<h1>@ViewData["Title"]</h1>

@if (Model.CancelSuccessful)
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-success">
                <p><strong>You've successfully cancelled a booking.</strong></p>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-md-12">
        <p>You are viewing upcoming bookings until @Model.EndOfWeek.ToString("D").</p>
    </div>
</div>

@foreach (var date in Model.CourtBookings)
{
    <div class="row">
        <div class="col-md-12">
            <h2>@date.Key.ToString("D")</h2>

            @foreach (var booking in date)
            {
                <div class="alert alert-info">
                    <p>
                        <strong>@booking.CourtName</strong>: @booking.StartDateTime.Hour.To12HourClockString() to @booking.EndDateTime.Hour.To12HourClockString()<br />
                        <em>@booking.MemberName</em>
                    </p>
                    <p>
                        <a asp-controller="Courts" asp-action="CancelBookingConfirmation" asp-route-bookingId="@booking.BookingId" class="btn btn-danger" role="button">
                            Cancel Booking
                        </a>
                    </p>
                </div>
            }
        </div>
    </div>
}